# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('abbreviation', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField(default=0)),
                ('contact_point', models.EmailField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('prefered_contact_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.ContactType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField(default=0)),
                ('contact_point', models.CharField(max_length=16)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.Participant')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.ContactType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='email',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.Participant'),
        ),
        migrations.AddField(
            model_name='email',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.ContactType'),
        ),
    ]
