# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20170222_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='type',
            field=models.CharField(choices=[('SMS', 'Text Message'), ('EMAIL', 'Email')], default='SMS', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.ContactType'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.ContactType'),
        ),
    ]
