# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20170222_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email Contact', 'verbose_name_plural': 'Email Contacts'},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': 'SMS Contact', 'verbose_name_plural': 'SMS Contacts'},
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('SMS', 'Text Message'), ('EMAIL', 'Email')], default='SMS', max_length=5),
        ),
        migrations.AlterField(
            model_name='participant',
            name='prefered_contact_method',
            field=models.CharField(choices=[('SMS', 'Text Message'), ('EMAIL', 'Email')], default='SMS', max_length=5),
        ),
        migrations.AlterField(
            model_name='sms',
            name='type',
            field=models.CharField(choices=[('SMS', 'Text Message'), ('EMAIL', 'Email')], default='SMS', max_length=5),
        ),
        migrations.DeleteModel(
            name='ContactType',
        ),
    ]
