# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20170222_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='contact_point',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='email',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.Participant'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.Participant'),
        ),
    ]
