# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20170223_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='deferential_delegation',
            field=models.BooleanField(default=False, help_text='only deletes should receive notifications'),
        ),
    ]
