# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:02
from __future__ import unicode_literals

from django.db import migrations, models

def split_full_name(apps, schema_editor):
    Participant = apps.get_model("scheduler", "Participant")
    for person in Participant.objects.all():
        name_parts = person.full_name.split()
        if len(name_parts) == 2:
            person.first_name = name_parts[0]
            person.last_name = name_parts[1]
            person.save()
        else:
            person.first_name = " ".join(name_parts[0:2])
            person.last_name = " ".join(name_parts[2:])

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_auto_20170225_1952'),
    ]

    operations = [
        migrations.RunPython(split_full_name),
    ]
