# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_auto_20170225_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
