# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0021_auto_20170225_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='direct_participant',
            field=models.BooleanField(default=True, help_text='Participant is a direct participant in the organization events'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
