# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_auto_20170318_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='prefered_contact_method',
            new_name='preferred_contact_method',
        ),
    ]
